[options]
; Path untuk addons
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons

; Direktori data Odoo
data_dir = /var/lib/odoo


; Konfigurasi database PostgreSQL
db_host = postgres_db
db_port = 5432
db_user = odoo_user
db_password = password_odoo123

; Filter database: HANYA tampilkan database dengan nama "odoo"
dbfilter = ^odoo_db$

; Nonaktifkan pilihan database (langsung gunakan database "odoo")
list_db = False

; Nama database default (opsional, tetapi direkomendasikan)
db_name = odoo_db

;timezone
timezone = Asia/Jakarta
